### ISSUE TITLE
Add a social media section for social media details

### ISSUE THREAD

**Issue by alfadelta10010** [acmpesuecc/readme-generator#10]
Add a new div maybe with input fields for social media account details

**Comment by udaykahar** [comment]
please assign it to me

**Comment by its-abhishek** [comment]
i have solved this issue plss assign to me

**Comment by Pai06** [comment]
pls assign it to me

**Comment by PavvanPradeep** [comment]
can you assign this to me

**Comment by sid-008** [comment]
@PavvanPradeep assigned

**Comment by Vaarun-Kamath** [comment]
can u assign me pls :)

**Comment by NavinShrinivas** [comment]
Ok, reassigning to @Vaarun-Kamath , no progress update from @PavvanPradeep.

**Comment by PavvanPradeep** [comment]
@NavinShrinivas @sid-008  im sorry i forgot to submit this code. im done with it. can I be assigned so I can submit

**Comment by NavinShrinivas** [comment]
ok, mergingn and closing issues!
