### ISSUE TITLE
Add animated background using vanta js

### ISSUE THREAD

**Issue by alfadelta10010** [acmpesuecc/readme-generator#11]
https://www.vantajs.com/

Use this site to try and add an animated background

**Comment by udaykahar** [comment]
i can work on it, please assign it to me

**Comment by its-abhishek** [comment]
I have completed the issue can I PR it plss assign me

**Comment by Vaarun-Kamath** [comment]
Hey can I have this pls :)

**Comment by siddarthpai** [comment]
hey can i work on this please

**Comment by sid-008** [comment]
@siddarthpai you can work on it

**Comment by AtharvaAnilChanda** [comment]
how long is the block time for this ??

**Comment by sid-008** [comment]
@AtharvaAnilChanda the block time for this issue is around an hour

**Comment by AtharvaAnilChanda** [comment]
can i be assigned to this now ??

**Comment by Tree1527** [comment]
Could I be assigned to this issue
Aditya Rajendra Shinde
PES2202200479

**Comment by its-abhishek** [comment]
plss assign this issue

**Comment by snaupdog** [comment]
Hey can i get this assigned to me
PES2202200828
Nihal Satish

**Comment by PavvanPradeep** [comment]
can i work on this?
