### ISSUE TITLE
Reformat the personal details section to make it nicer

### ISSUE THREAD

**Issue by alfadelta10010** [acmpesuecc/readme-generator#8]
make sections for form responses eg:
Hi I am "name" and I am working on "name"
add more stuff that gives an insight on the user's personality etc
contact @sid-008 for details

**Comment by PavvanPradeep** [comment]
can i work on this

**Comment by Hasika-11** [comment]
can i work on this

**Comment by sid-008** [comment]
@Hasika-11 can work on this

**Comment by AtharvaAnilChanda** [comment]
Heyy , can this be assigned to me ?? 
Atharva Anil Chanda 
PES2UG0CS075

**Comment by nik2203** [comment]
hi, can i be added to this
PES2UG21CS334
Nikhil Girish

**Comment by sid-008** [comment]
The issue has already been blocked @nik2203 @AtharvaAnilChanda, please wait for minimum 30min

**Comment by Tree1527** [comment]
Could I be assigned to this issue
Aditya Rajendra Shinde
PES2202200479

**Comment by its-abhishek** [comment]
plss assign this issue

**Comment by siddarthpai** [comment]
hey can i work on it

**Comment by sid-008** [comment]
Unfortunately this issue has been closed
